name: Create Pre-Release

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    permissions: write-all
    
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build distribution with Gradle
        run: ./gradlew distZip
        
      - name: Decompress distribution zip file
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq Kepler-Server/build/distributions/Kepler-Server.zip -d ./release
          
      - name: File release preparation
        run: |
          sudo rm -rf ./release/Kepler-Server/bin/*
          sudo rm -rf ./release/Kepler-Server/bin
          sudo mkdir ./Kepler
          sudo mkdir ./Kepler/lib
          sudo mv ./release/Kepler-Server/lib/Kepler-Server.jar ./Kepler/kepler.jar
          sudo mv ./release/Kepler-Server/lib/* ./Kepler/lib
          sudo cp tools/scripts/run.bat ./Kepler/
          sudo cp tools/scripts/run.sh ./Kepler/

      - id: sha-short
        name: Get short SHA
        run: echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
        
      - name: Compress release files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./Kepler-${{ steps.sha-short.outputs.sha-short }}.zip ./Kepler
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ steps.sha-short.outputs.sha-short }}"
          files: |
            Kepler-${{ steps.sha-short.outputs.sha-short }}.zip